# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_status', models.CharField(max_length=10)),
                ('project_completion', models.IntegerField()),
            ],
        ),
    ]
