# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0003_auto_20160305_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
