# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 17:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0004_auto_20160305_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('check_items', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_true_checks', models.IntegerField(validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)])),
                ('check_items_1', models.CharField(max_length=1000)),
                ('check_items_2', models.CharField(max_length=1000)),
                ('check_items_3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='stagesetting',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Project'),
        ),
    ]
