# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0005_auto_20160306_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='check_items',
            new_name='stage_item',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='in_stage',
            new_name='stage_number',
        ),
        migrations.RenameField(
            model_name='stagesetting',
            old_name='check_items_1',
            new_name='checked_items',
        ),
        migrations.RemoveField(
            model_name='stagesetting',
            name='check_items_2',
        ),
        migrations.RemoveField(
            model_name='stagesetting',
            name='check_items_3',
        ),
    ]
