# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 08:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0006_auto_20160307_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagesetting',
            name='total_true_checks',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
    ]
