# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0007_auto_20160307_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_item',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
