# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0010_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Role'),
        ),
    ]
