# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0013_auto_20160307_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
