# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0014_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=50)),
                ('member_role', models.CharField(max_length=50)),
            ],
        ),
    ]
