# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0015_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
