# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0016_auto_20160308_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Role')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Project')),
            ],
        ),
    ]
