# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0017_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_plan', models.CharField(max_length=1000)),
                ('business_plan', models.CharField(max_length=1000)),
                ('wiki_link', models.CharField(max_length=1000)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Project')),
            ],
        ),
    ]
