# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0018_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='business_plan',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='project_plan',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='wiki_link',
            field=models.URLField(max_length=1000),
        ),
    ]
