# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0021_auto_20160319_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(),
        ),
    ]
