# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0026_auto_20160328_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='status_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
