# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0027_orderstatus_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photo')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Project')),
            ],
        ),
    ]
