# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0028_prototype'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='prototype_url',
            field=models.URLField(default=datetime.datetime(2016, 4, 9, 17, 30, 43, 830000, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='weblink_url',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
