# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0029_auto_20160409_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('commented_on', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=2000)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Material')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('commented_on', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=2000)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='business_plan',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='project_plan',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='prototype_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='weblink_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='wiki_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
