# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0032_auto_20160410_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='order_vendor',
            field=models.CharField(default='Amazon', max_length=500),
        ),
    ]
