# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0033_material_order_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='order_currency',
            field=models.CharField(default='Rs', max_length=5),
        ),
    ]
