# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0036_trackinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinginfo',
            name='courier_id',
        ),
        migrations.RemoveField(
            model_name='trackinginfo',
            name='material',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='TrackingInfo',
        ),
    ]
