# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0038_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, max_length=50)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Courier')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Material')),
            ],
        ),
    ]
