# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 03:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0039_trackinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='order_currency',
            field=models.CharField(blank=True, default='Rs', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='order_quantity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='order_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='order_vendor',
            field=models.CharField(blank=True, default='Amazon', max_length=500, null=True),
        ),
    ]
