# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0040_auto_20170713_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='author',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
