# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0041_material_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='est_lead_time',
            field=models.CharField(default='1d', max_length=10),
            preserve_default=False,
        ),
    ]
