# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0042_material_est_lead_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
