# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0043_orderlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlisting',
            name='category',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='orderlisting',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='orderlisting',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
