# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0045_auto_20170717_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VendorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderListing',
        ),
    ]
