# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0046_auto_20170718_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoryList',
        ),
        migrations.RenameField(
            model_name='vendorlist',
            old_name='vendor',
            new_name='vendor_name',
        ),
        migrations.AddField(
            model_name='categorylist',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorlist',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorlist',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorlist',
            name='contact_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorlist',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
