# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0047_auto_20170719_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
