# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0049_orderpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='order_priority',
            field=models.ForeignKey(default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpm.OrderPriority'),
        ),
    ]
