# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0054_auto_20170802_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadCommentTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('read_flag', models.CharField(default='N', max_length=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpm.Material')),
            ],
        ),
    ]
