# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0055_readcommenttrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readcommenttrack',
            name='material',
        ),
        migrations.AddField(
            model_name='readcommenttrack',
            name='order_id',
            field=models.IntegerField(default='96'),
            preserve_default=False,
        ),
    ]
